### ISSUE TITLE
Update Map UI with LTER sites

### ISSUE THREAD

**Issue by tyson-swetnam** [cyverse-gis/suas-metadata#16]
The LTER network has what appears to be an API webservice: https://portal.edirepository.org/nis/home.jsp

The sites are visible in this map, but I'm not sure where the file is: https://lternet.edu/site/

**Comment by priggec** [comment]
I've looked into this at greater length. It does not appear that the database has an api that can be queried for LTER site info/polygons. We could probably still grab it from the site, but it would probably just be more effective to download them manually and add them to Calliope like the USFS and LTAR sites.

**Comment by priggec** [comment]
Upon further review, the sites appear to all have their own different websites. There is no queriable or even downloadable polygon or data. The polygons shown on the site linked are hardcoded and not read from any data source. We could possibly trawl through the map there and try to save off the html elements, but I think it might just not be possible to get the LTER sites for now.

**Comment by tyson-swetnam** [comment]
Let's move this to Closed - there is no solution and we don't have a pressing use case right now.
