### ISSUE TITLE
Image Collection Editor (pop up window) does not scale text size

### ISSUE THREAD

**Issue by tyson-swetnam** [cyverse-gis/suas-metadata#70]
When the text size scaling is changed from 100%, e.g. to 300%, the Image Collection Editor, which appears when you click on the My Collections 'Gear', the text in the pop up window is still small.![Screenshot from 2019-07-30 13-21-15.png](https://images.zenhubusercontent.com/5c475f1518676310d6667169/41715a50-912e-43fb-915f-f5dc331b6288)

**Comment by JLHonors** [comment]
This may apply to pop-up windows in general.
